Add more implementation & proofs for trusty API
seahorn/verifyTrusty pull request #10
Opened 2021-05-28 03:45 UTC by LinerSu

- Add more unit proofs: `wait_any`, `accept`, `close`, `get_msg`, `put_msg`, `send_msg`, and `read_msg`.
- Update implementation of API (for `accept`, `connect`)
- Fix post conditions declared in `connect` proof.

2021-05-28 14:58 UTC, agurfinkel commented on seahorn/trusty/user/base/lib/libc-trusty/sea_handle_table.c
> +  if ((strcmp(PHANDLE(X, path), path) == 0) && PHANDLE(X, active))             \
this is too expensive. we can't have this in the model. no `memcmp` and definitely no `strcmp`.

If you need paths, restrict them to be one character length

2021-05-28 15:02 UTC, agurfinkel requested changes
LGTM overall. 

The use of strcmp should be replaced by checking only the first character of the string.
Probably the input path string should be copied (again, only its first character)
`cex` fails in CI, needs to be addressed. Maybe using `smtfd` or `explicit_sp0` or both.

2021-05-31 19:41 UTC, agurfinkel requested changes
LGTM

Only required change is to not enable explicit sp0 globally

2021-05-31 19:41 UTC, agurfinkel commented on .github/workflows/main.yml
> +        verify_flag: ["", "--vac", "--cex --horn-explicit-sp0=true"]
we do not need `explicit-sp0` for all jobs. Only for some. Please add it only when necessary. It under approximates some behaviours. I am still unsure whether using it all the time will not miss some bugs.

2021-06-01 01:29 UTC, LinerSu commented
Fixed it by splitting `ctest` under `cex` mode.

2021-06-01 01:55 UTC, agurfinkel requested changes

2021-06-01 01:55 UTC, agurfinkel commented on .github/workflows/main.yml
> +      - if: ${{ matrix.verify_flag == '--cex' }}
no. this only applies in CI. We specifically have local sea.yaml files to change options per individual proof. Please use these.

2021-06-01 21:01 UTC, LinerSu commented
DONE!!!

2021-06-02 12:38 UTC, agurfinkel approved these changes

2021-06-02 12:39 UTC, merged